### ISSUE TITLE
Card implementation and link text - DAC_Non-descriptive_Links_Issue3

### ISSUE THREAD

**Issue by gtvj** [nationalarchives/ds-wagtail#171]
On page 22 of the report DAC describe an issue with ID `DAC_Non-descriptive_Links_Issue3`. The full description needs to be read to be understood (I won't try to summarise it here) but this does not seem to relate to a WCAG success criterion.

To address the issues which are described (including those that are included in the analyst comments), I suggest we need to:

- to update all card components so that the link text includes only what is necessary (some new styling may be necessary and we'll need to test the impact of this change quite thoroughly). **This might be easiest to achieve through a co-design session, but it might be sufficient to just include the heading text**. Once we have come up with a solution and implemented it, we will need to do a review of the pages to ensure all links are sufficiently well described (and not duplicated).
- remove the use of `<figure>` and `<figcaption>` elements from cards (on the basis that the images within the `<figure>` element is hidden from assistive technology by an empty `alt` attribute. 

A separate issue is mentioned for JAWS users where "group start" is announced. According to the [JAWS documentation](https://freedomscientific.github.io/VFO-standards-support/html.html), the voice UI only announces this when it encounters a `<fieldset>` and I wonder if this might be a bug which has arisen from the use of `<figure>` that contains an image with an empty `alt` (that is very much a guess though). We should explore this further too.

### Why wasn't this picked up in in-house testing
It doesn't seem to relate to any Level A or Level AA success criteria

**Comment by gtvj** [comment]
Hi @AshTNA,

On the proposals above: 

-  I'm not sure about how the screenshot above looks (it seems a bit odd to me that the description is outside of the card when focused). I feel like the cards need to be redesigned so that, perhaps, it is only the title which is the link (and which has a focus/hover state). This is definitely something to be discussed from a design perspective though. 
- My sense is that it's not necessary to provide a separate field for editors to add a `sr-only` field and that it _might_ be better to update the editorial interface to explain that any titles entered should be understandable when encountered both in and out of context

Would you mind setting up a co-design session with visual/content design (so that we can look at all cards)? We could then seek all the relevant viewpoints. It might be helpful if we could present some options during the meeting.

**Comment by AshTNA** [comment]
Sounds good - thanks @gtvj, will do :+1:
