### ISSUE TITLE
Links within hierarchy local - DAC_Non-descriptive_Links_Issue4

### ISSUE THREAD

**Issue by gtvj** [nationalarchives/ds-wagtail#172]
On page 26 of the report DAC describe an issue with ID `DAC_Non-descriptive_Links_Issue4` which says the purpose of the links within should be contained in the link itself. The report doesn't specify which WCAG Success Criterion this relates to but, since the required text is provided in the programatically determined context (which would, I think, meet [Success Criterion 2.4.4 Link Purpose (In context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html), it seems this might be [Success Criterion 2.4.9 Link Purpose (Link only) at Level AAA](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-link-only)

DAC have suggested we fix this by introducing a `sr-only` `<span>` element that contains the information "Previous", "Next" and "This record is in" statements for each link. 

I'm not entirely sure about this approach because I'd have thought it might lead to users encountering the same information twice as they move through the page in context, for example: "This record is in This record is in ...". I wonder whether it would be better to simply bring the visually shown text into the link. 

### Why wasn't this picked up by in-house testing
It seems to relate to a Level AAA success criterion.

**Comment by matt-blair** [comment]
A solution to this could be to wrap the whole element in an <a> tag and add a span to ensure the generic descriptive text in the link 'i.e previous record, this record is in, etc' is styled slightly differently and on a separate line. That would allow the link to be fully descriptive out-of-context in a list of links, but retain the control of the unique part of the link which is helpful for readability to differentiate on the visual interface.
