### ISSUE TITLE
Images of text - DAC_Images_Of_Text_Issue1

### ISSUE THREAD

**Issue by gtvj** [nationalarchives/ds-wagtail#176]
On page 35 of the report DAC describe an issue with ID `DAC_Images_Of_Text_Issue1`. It is described as a failure of [Success Criterion 1.4.5 Images of text (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html) and [Success Criterion 1.4.9 Images of text - No Exception (Level AAA)](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text-no-exception.html). The key issue is made in relation to [this image of a typed letter](https://beta.nationalarchives.gov.uk/insight-pages/noor-inayat-khan/#analytics-blog-embed-3) and says: 

> _The image containing an image of a letter, provides users with a section of text which users can read; however, this text is not provided in any other means other than in the image. Some users rely on altering the font, colour and size of text in order to be able to read and understand the content. As this is only provided as an image, these functions are not available. In addition, blind users are only presented with an alt attribute which does not provide users with the text content, but instead, provides a description of the document._

The led to further discussion and clarification from DAC (all outlined below) but it seems the only appropriate response is to: 

* Update the TNA content guidelines to ensure images of documents have `alt` text which reflects what DAC have suggested (i.e. the text of the document which is represented in the image)
* Go through all the images of documents in Etna interpretive content and update them accordingly.

### Why was this issue not identified by in-house testing
It had understood this to be a visual representation of the record (to reinforce that there is a physical object within the archive) rather than something a user would read.

**Comment by gtvj** [comment]
I'm just reviewing the GitHub issues and noticed that this one is still open. I've just emailed DAC today to ask if there is any update.

**Comment by gtvj** [comment]
The response from DAC received yesterday says: 

> In regards to the exemption for the large numbers of the images containing text, this meets the requirements for the exemption of ‘disproportionate burden’ for all currently uploaded and added images. However, for all images added in the future, they must be individually assessed and are not exempt as they are added individually, allowing each image to individually assessed by yourselves and determine if you feel the image needs a text alternative

I'm not sure that 'disproportionate burden' is applicable here because it's interpretive content added via the CMS and would appear to fall well below the threshold of effort to support such a claim. For images within details page and the image viewer, I expect [Section 4(2)(f) of Public Sector Bodies Accessibility Regulations](https://www.legislation.gov.uk/uksi/2018/952/regulation/4/made) would apply. 

The implications here for Etna are quite significant because so many of the images we'll have will be representations of documents within the collection - and may therefore be readable to sighted users (which would constitute a Level A failure if they don't have a text alternative). 

I think the team are going to need to decide how to proceed and get input from senior stakeholders.

cc. @sdwilkes @piriyapordes @matt-blair @jklepfer @ruthroberts @matt-blair

**Comment by gtvj** [comment]
This was discussed at the Operations Meeting on 24 November where @sdwilkes suggested seeking advice from a policy / interpretation perspective. @catherinelliott will mention this in a 1:1.

**Comment by gtvj** [comment]
This was discussed at the Operations Meeting on 6 January where Catherine explained it has been discussed at Director level and is acknowledged to be a something that needs to be solved for the organisation. The intention is to explore at the organisation level what might be achieved via artificial intelligence/machine learning/OCR/HTR etc. but this may not be achievable within the timescales of open Beta. 

It seems the only appropriate response is to:

* Update the TNA content guidelines to reflect the need for images of documents to have alt text which reflects what DAC have suggested (i.e. the text of the document which is represented in the image)
* Review all the images of documents in Etna CMS content and update them accordingly.

**Comment by jamesbiggs** [comment]
I think we can close this issue now, it'll be stored in closed issues if it needs to be reopened for any reason.
