### ISSUE TITLE
Illogical heading structure - DAC_Illogical_Heading_Structure_Issue1

### ISSUE THREAD

**Issue by gtvj** [nationalarchives/ds-wagtail#184]
On page 52 of the report DAC have identified an issue with ID `DAC_Illogical_Heading_Structure_Issue1` that relates to skipped heading levels that exist on the introduction page. While this page is not actually part of the pubic facing service, it does reflect an issue that will grow with time if we don't do something soon. 

We can fix this by ensuring that reusable components which editors can freely place within a page: 

* Allow the editor to select an appropriate heading level 
* Are provided with hint text that explains to editors the importance of a meaningful heading level

@JamesWChan has started to explore this but it may be that additional advice and support is needed under the Wagtail specialist contract.

**Note:** while DAC have identified this as a Level AAA failure I also suspect it may result in other failures under [Success Criterion 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships)

### Why was this not picked up in the in-house testing? 

We knew about this issue and that it was only present on this non-service page. I thought we'd asked for this page not to be tested. That said, it is an issue that we knew needed to be fixed.

**Comment by JamesWChan** [comment]
This has been addressed by allowing editors to select from a range of headings in the Wagtail editorial interface so that the appropriate heading tag is used and doesn't cause the heading structure to break.
